server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  access:
    secret: f8a7c2e1b5d943f28a1c6e4d9f0b3a7c
    ttl: 900000      # 15 minutes (ms)
  refresh:
    secret: 3d9f7b2c1e5a48f6b0d2c9e7f4a1b6c8
    ttl: 1209600000 # 14 days (ms)
